# Generated by Django 2.1.3 on 2019-06-26 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city_office',
            fields=[
                ('city_office_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_office_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='city_office_staff',
            fields=[
                ('city_office_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_office_staff_name', models.CharField(max_length=255)),
                ('city_office_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_city_office_id', to='backend_api.city_office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='health_center',
            fields=[
                ('health_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_center_name', models.CharField(max_length=2555)),
                ('health_center_location', models.CharField(max_length=255)),
                ('city_office_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='center_city_office_id', to='backend_api.city_office')),
            ],
        ),
        migrations.CreateModel(
            name='health_center_staff',
            fields=[
                ('health_center_staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_center_staff_name', models.CharField(max_length=255)),
                ('health_center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_health_center_id', to='backend_api.health_center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('product_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('current_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('starting_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('health_center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_health_center_id', to='backend_api.health_center')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order_status', models.CharField(choices=[('Ordered', 'Ordered'), ('Received', 'Received'), ('Confirmed', 'Confirmed'), ('Dispatched', 'Dispatched')], max_length=255)),
                ('city_office_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_city_office_id', to='backend_api.city_office')),
                ('health_center_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_health_center_id', to='backend_api.health_center')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product_code', to='backend_api.inventory')),
            ],
        ),
    ]
