# Generated by Django 2.1.3 on 2019-06-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('received', 'Received'), ('ordered', 'Ordered'), ('approved', 'Approved'), ('delivered', 'Delivered')], max_length=255),
        ),
    ]
